//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test_work.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tovar
    {
        public int id_tovar { get; set; }
        public string Name_tovar { get; set; }
        public string Price_tovar { get; set; }
    }
}
